

services:
  mysql:
    image: mysql:8
    container_name: Malshinon-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Malshinon
      MYSQL_USER: intel_user
      MYSQL_PASSWORD: intelpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
